//import uuid from "react-native-uuid";

export interface Audit {
  _id: string; // remains the string type (generated by uuid())
  // refactored because we dont intend to change data and at
  // this point, doing it properly is too much for our work capacity
}
