name: Static Analysis

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Run ESLint for static analysis
        run: npm run lint
        working-directory: ./src

      - name: Run Prettier for code formatting check
        run: npx prettier --check .
        working-directory: ./src

      - name: Install React Native dependencies
        run: npm install --save react-native
        working-directory: ./src

      - name: Run React Native lint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
        working-directory: ./src
